# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'jr_armcontrol.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainForm(object):
    def setupUi(self, MainForm):
        if not MainForm.objectName():
            MainForm.setObjectName(u"MainForm")
        MainForm.resize(1048, 880)
        font = QFont()
        font.setFamily(u"Arial")
        font.setPointSize(11)
        MainForm.setFont(font)
        self.gbUnit = QGroupBox(MainForm)
        self.gbUnit.setObjectName(u"gbUnit")
        self.gbUnit.setGeometry(QRect(20, 20, 351, 851))
        self.gbUnit.setFont(font)
        self.cbPort = QComboBox(self.gbUnit)
        self.cbPort.setObjectName(u"cbPort")
        self.cbPort.setGeometry(QRect(80, 20, 150, 30))
        self.lbPort = QLabel(self.gbUnit)
        self.lbPort.setObjectName(u"lbPort")
        self.lbPort.setGeometry(QRect(10, 20, 71, 31))
        self.lbPort.setAlignment(Qt.AlignCenter)
        self.btnConnect = QPushButton(self.gbUnit)
        self.btnConnect.setObjectName(u"btnConnect")
        self.btnConnect.setGeometry(QRect(240, 20, 91, 71))
        self.btnConnect.setStyleSheet(u"")
        self.lbBaudRate = QLabel(self.gbUnit)
        self.lbBaudRate.setObjectName(u"lbBaudRate")
        self.lbBaudRate.setGeometry(QRect(10, 60, 71, 31))
        self.lbBaudRate.setAlignment(Qt.AlignCenter)
        self.cbBaudRate = QComboBox(self.gbUnit)
        self.cbBaudRate.setObjectName(u"cbBaudRate")
        self.cbBaudRate.setGeometry(QRect(80, 60, 150, 30))
        self.gbCurrentPos = QGroupBox(self.gbUnit)
        self.gbCurrentPos.setObjectName(u"gbCurrentPos")
        self.gbCurrentPos.setGeometry(QRect(10, 120, 331, 221))
        self.lbCurrentPosJoint4 = QLabel(self.gbCurrentPos)
        self.lbCurrentPosJoint4.setObjectName(u"lbCurrentPosJoint4")
        self.lbCurrentPosJoint4.setGeometry(QRect(10, 180, 71, 31))
        self.lbCurrentPosJoint4.setAlignment(Qt.AlignCenter)
        self.lbCurrentPosJoint1 = QLabel(self.gbCurrentPos)
        self.lbCurrentPosJoint1.setObjectName(u"lbCurrentPosJoint1")
        self.lbCurrentPosJoint1.setGeometry(QRect(0, 30, 91, 31))
        self.lbCurrentPosJoint1.setFont(font)
        self.lbCurrentPosJoint1.setMouseTracking(False)
        self.lbCurrentPosJoint1.setAlignment(Qt.AlignCenter)
        self.lbCurrentPosJoint2 = QLabel(self.gbCurrentPos)
        self.lbCurrentPosJoint2.setObjectName(u"lbCurrentPosJoint2")
        self.lbCurrentPosJoint2.setGeometry(QRect(10, 80, 71, 31))
        self.lbCurrentPosJoint2.setAlignment(Qt.AlignCenter)
        self.tbCurrentPosJoint1 = QPlainTextEdit(self.gbCurrentPos)
        self.tbCurrentPosJoint1.setObjectName(u"tbCurrentPosJoint1")
        self.tbCurrentPosJoint1.setGeometry(QRect(100, 30, 220, 31))
        self.tbCurrentPosJoint4 = QPlainTextEdit(self.gbCurrentPos)
        self.tbCurrentPosJoint4.setObjectName(u"tbCurrentPosJoint4")
        self.tbCurrentPosJoint4.setGeometry(QRect(100, 180, 220, 31))
        self.lbCurrentPosJoint3 = QLabel(self.gbCurrentPos)
        self.lbCurrentPosJoint3.setObjectName(u"lbCurrentPosJoint3")
        self.lbCurrentPosJoint3.setGeometry(QRect(10, 130, 71, 31))
        self.lbCurrentPosJoint3.setAlignment(Qt.AlignCenter)
        self.tbCurrentPosJoint3 = QPlainTextEdit(self.gbCurrentPos)
        self.tbCurrentPosJoint3.setObjectName(u"tbCurrentPosJoint3")
        self.tbCurrentPosJoint3.setGeometry(QRect(100, 130, 220, 31))
        self.tbCurrentPosJoint2 = QPlainTextEdit(self.gbCurrentPos)
        self.tbCurrentPosJoint2.setObjectName(u"tbCurrentPosJoint2")
        self.tbCurrentPosJoint2.setGeometry(QRect(100, 80, 220, 31))
        self.gbCurrentPos_2 = QGroupBox(self.gbUnit)
        self.gbCurrentPos_2.setObjectName(u"gbCurrentPos_2")
        self.gbCurrentPos_2.setGeometry(QRect(10, 340, 331, 221))
        self.lbTargetPosJoint4 = QLabel(self.gbCurrentPos_2)
        self.lbTargetPosJoint4.setObjectName(u"lbTargetPosJoint4")
        self.lbTargetPosJoint4.setGeometry(QRect(10, 180, 51, 31))
        self.lbTargetPosJoint4.setAlignment(Qt.AlignCenter)
        self.lbTargetPosJoint1 = QLabel(self.gbCurrentPos_2)
        self.lbTargetPosJoint1.setObjectName(u"lbTargetPosJoint1")
        self.lbTargetPosJoint1.setGeometry(QRect(10, 30, 51, 31))
        self.lbTargetPosJoint1.setFont(font)
        self.lbTargetPosJoint1.setMouseTracking(False)
        self.lbTargetPosJoint1.setAlignment(Qt.AlignCenter)
        self.lbTargetPosJoint2 = QLabel(self.gbCurrentPos_2)
        self.lbTargetPosJoint2.setObjectName(u"lbTargetPosJoint2")
        self.lbTargetPosJoint2.setGeometry(QRect(10, 80, 51, 31))
        self.lbTargetPosJoint2.setAlignment(Qt.AlignCenter)
        self.tbTargetPosJoint1 = QPlainTextEdit(self.gbCurrentPos_2)
        self.tbTargetPosJoint1.setObjectName(u"tbTargetPosJoint1")
        self.tbTargetPosJoint1.setGeometry(QRect(70, 30, 140, 31))
        self.tbTargetPosJoint4 = QPlainTextEdit(self.gbCurrentPos_2)
        self.tbTargetPosJoint4.setObjectName(u"tbTargetPosJoint4")
        self.tbTargetPosJoint4.setGeometry(QRect(70, 180, 140, 31))
        self.lbTargetPosJoint3 = QLabel(self.gbCurrentPos_2)
        self.lbTargetPosJoint3.setObjectName(u"lbTargetPosJoint3")
        self.lbTargetPosJoint3.setGeometry(QRect(10, 130, 51, 31))
        self.lbTargetPosJoint3.setAlignment(Qt.AlignCenter)
        self.tbTargetPosJoint3 = QPlainTextEdit(self.gbCurrentPos_2)
        self.tbTargetPosJoint3.setObjectName(u"tbTargetPosJoint3")
        self.tbTargetPosJoint3.setGeometry(QRect(70, 130, 140, 31))
        self.tbTargetPosJoint2 = QPlainTextEdit(self.gbCurrentPos_2)
        self.tbTargetPosJoint2.setObjectName(u"tbTargetPosJoint2")
        self.tbTargetPosJoint2.setGeometry(QRect(70, 80, 140, 31))
        self.btnMoveJoint1 = QPushButton(self.gbCurrentPos_2)
        self.btnMoveJoint1.setObjectName(u"btnMoveJoint1")
        self.btnMoveJoint1.setGeometry(QRect(220, 20, 101, 41))
        self.btnMoveJoint2 = QPushButton(self.gbCurrentPos_2)
        self.btnMoveJoint2.setObjectName(u"btnMoveJoint2")
        self.btnMoveJoint2.setGeometry(QRect(220, 70, 101, 41))
        self.btnMoveJoint3 = QPushButton(self.gbCurrentPos_2)
        self.btnMoveJoint3.setObjectName(u"btnMoveJoint3")
        self.btnMoveJoint3.setGeometry(QRect(220, 120, 101, 41))
        self.btnMoveJoint4 = QPushButton(self.gbCurrentPos_2)
        self.btnMoveJoint4.setObjectName(u"btnMoveJoint4")
        self.btnMoveJoint4.setGeometry(QRect(220, 170, 101, 41))
        self.gbInitParam = QGroupBox(MainForm)
        self.gbInitParam.setObjectName(u"gbInitParam")
        self.gbInitParam.setGeometry(QRect(380, 120, 641, 161))
        self.tbCurrentPosJoint2_3 = QPlainTextEdit(self.gbInitParam)
        self.tbCurrentPosJoint2_3.setObjectName(u"tbCurrentPosJoint2_3")
        self.tbCurrentPosJoint2_3.setGeometry(QRect(80, 100, 140, 31))
        self.lbInitPos_Z = QLabel(self.gbInitParam)
        self.lbInitPos_Z.setObjectName(u"lbInitPos_Z")
        self.lbInitPos_Z.setGeometry(QRect(20, 100, 51, 31))
        self.lbInitPos_Z.setAlignment(Qt.AlignCenter)
        self.tbCurrentPosJoint1_3 = QPlainTextEdit(self.gbInitParam)
        self.tbCurrentPosJoint1_3.setObjectName(u"tbCurrentPosJoint1_3")
        self.tbCurrentPosJoint1_3.setGeometry(QRect(80, 40, 140, 31))
        self.lbInitPos_X = QLabel(self.gbInitParam)
        self.lbInitPos_X.setObjectName(u"lbInitPos_X")
        self.lbInitPos_X.setGeometry(QRect(20, 40, 51, 31))
        self.lbInitPos_X.setFont(font)
        self.lbInitPos_X.setMouseTracking(False)
        self.lbInitPos_X.setAlignment(Qt.AlignCenter)
        self.tbCurrentPosJoint2_4 = QPlainTextEdit(self.gbInitParam)
        self.tbCurrentPosJoint2_4.setObjectName(u"tbCurrentPosJoint2_4")
        self.tbCurrentPosJoint2_4.setGeometry(QRect(290, 100, 140, 31))
        self.lbInitPos_Rx = QLabel(self.gbInitParam)
        self.lbInitPos_Rx.setObjectName(u"lbInitPos_Rx")
        self.lbInitPos_Rx.setGeometry(QRect(230, 100, 51, 31))
        self.lbInitPos_Rx.setAlignment(Qt.AlignCenter)
        self.tbCurrentPosJoint1_4 = QPlainTextEdit(self.gbInitParam)
        self.tbCurrentPosJoint1_4.setObjectName(u"tbCurrentPosJoint1_4")
        self.tbCurrentPosJoint1_4.setGeometry(QRect(290, 40, 140, 31))
        self.lbInitPos_Y = QLabel(self.gbInitParam)
        self.lbInitPos_Y.setObjectName(u"lbInitPos_Y")
        self.lbInitPos_Y.setGeometry(QRect(230, 40, 51, 31))
        self.lbInitPos_Y.setFont(font)
        self.lbInitPos_Y.setMouseTracking(False)
        self.lbInitPos_Y.setAlignment(Qt.AlignCenter)
        self.btnMoveInitPos = QPushButton(self.gbInitParam)
        self.btnMoveInitPos.setObjectName(u"btnMoveInitPos")
        self.btnMoveInitPos.setGeometry(QRect(440, 30, 80, 110))
        self.btnSaveInitPos = QPushButton(self.gbInitParam)
        self.btnSaveInitPos.setObjectName(u"btnSaveInitPos")
        self.btnSaveInitPos.setGeometry(QRect(550, 30, 70, 110))
        self.gbWaitParam = QGroupBox(MainForm)
        self.gbWaitParam.setObjectName(u"gbWaitParam")
        self.gbWaitParam.setGeometry(QRect(380, 290, 641, 161))
        self.lbWaitPos_Z = QLabel(self.gbWaitParam)
        self.lbWaitPos_Z.setObjectName(u"lbWaitPos_Z")
        self.lbWaitPos_Z.setGeometry(QRect(20, 100, 51, 31))
        self.lbWaitPos_Z.setAlignment(Qt.AlignCenter)
        self.tbCurrentPosJoint1_5 = QPlainTextEdit(self.gbWaitParam)
        self.tbCurrentPosJoint1_5.setObjectName(u"tbCurrentPosJoint1_5")
        self.tbCurrentPosJoint1_5.setGeometry(QRect(290, 40, 140, 31))
        self.lbWaitPos_X = QLabel(self.gbWaitParam)
        self.lbWaitPos_X.setObjectName(u"lbWaitPos_X")
        self.lbWaitPos_X.setGeometry(QRect(20, 40, 51, 31))
        self.lbWaitPos_X.setFont(font)
        self.lbWaitPos_X.setMouseTracking(False)
        self.lbWaitPos_X.setAlignment(Qt.AlignCenter)
        self.lbWaitPos_Y = QLabel(self.gbWaitParam)
        self.lbWaitPos_Y.setObjectName(u"lbWaitPos_Y")
        self.lbWaitPos_Y.setGeometry(QRect(230, 40, 51, 31))
        self.lbWaitPos_Y.setFont(font)
        self.lbWaitPos_Y.setMouseTracking(False)
        self.lbWaitPos_Y.setAlignment(Qt.AlignCenter)
        self.tbCurrentPosJoint2_5 = QPlainTextEdit(self.gbWaitParam)
        self.tbCurrentPosJoint2_5.setObjectName(u"tbCurrentPosJoint2_5")
        self.tbCurrentPosJoint2_5.setGeometry(QRect(80, 100, 140, 31))
        self.tbCurrentPosJoint1_6 = QPlainTextEdit(self.gbWaitParam)
        self.tbCurrentPosJoint1_6.setObjectName(u"tbCurrentPosJoint1_6")
        self.tbCurrentPosJoint1_6.setGeometry(QRect(80, 40, 140, 31))
        self.tbCurrentPosJoint2_6 = QPlainTextEdit(self.gbWaitParam)
        self.tbCurrentPosJoint2_6.setObjectName(u"tbCurrentPosJoint2_6")
        self.tbCurrentPosJoint2_6.setGeometry(QRect(290, 100, 140, 31))
        self.lbWaitPos_Rx = QLabel(self.gbWaitParam)
        self.lbWaitPos_Rx.setObjectName(u"lbWaitPos_Rx")
        self.lbWaitPos_Rx.setGeometry(QRect(230, 100, 51, 31))
        self.lbWaitPos_Rx.setAlignment(Qt.AlignCenter)
        self.btnMoveWaitPos = QPushButton(self.gbWaitParam)
        self.btnMoveWaitPos.setObjectName(u"btnMoveWaitPos")
        self.btnMoveWaitPos.setGeometry(QRect(440, 30, 80, 110))
        self.btnSaveWaitPos = QPushButton(self.gbWaitParam)
        self.btnSaveWaitPos.setObjectName(u"btnSaveWaitPos")
        self.btnSaveWaitPos.setGeometry(QRect(550, 30, 70, 110))
        self.gbTargetParam = QGroupBox(MainForm)
        self.gbTargetParam.setObjectName(u"gbTargetParam")
        self.gbTargetParam.setGeometry(QRect(380, 460, 641, 161))
        self.lbTargetPos_Z = QLabel(self.gbTargetParam)
        self.lbTargetPos_Z.setObjectName(u"lbTargetPos_Z")
        self.lbTargetPos_Z.setGeometry(QRect(20, 100, 51, 31))
        self.lbTargetPos_Z.setAlignment(Qt.AlignCenter)
        self.tbCurrentPosJoint1_7 = QPlainTextEdit(self.gbTargetParam)
        self.tbCurrentPosJoint1_7.setObjectName(u"tbCurrentPosJoint1_7")
        self.tbCurrentPosJoint1_7.setGeometry(QRect(290, 40, 140, 31))
        self.lbTargetPos_X = QLabel(self.gbTargetParam)
        self.lbTargetPos_X.setObjectName(u"lbTargetPos_X")
        self.lbTargetPos_X.setGeometry(QRect(20, 40, 51, 31))
        self.lbTargetPos_X.setFont(font)
        self.lbTargetPos_X.setMouseTracking(False)
        self.lbTargetPos_X.setAlignment(Qt.AlignCenter)
        self.lbTargetPos_Y = QLabel(self.gbTargetParam)
        self.lbTargetPos_Y.setObjectName(u"lbTargetPos_Y")
        self.lbTargetPos_Y.setGeometry(QRect(230, 40, 51, 31))
        self.lbTargetPos_Y.setFont(font)
        self.lbTargetPos_Y.setMouseTracking(False)
        self.lbTargetPos_Y.setAlignment(Qt.AlignCenter)
        self.tbCurrentPosJoint2_7 = QPlainTextEdit(self.gbTargetParam)
        self.tbCurrentPosJoint2_7.setObjectName(u"tbCurrentPosJoint2_7")
        self.tbCurrentPosJoint2_7.setGeometry(QRect(80, 100, 140, 31))
        self.tbCurrentPosJoint1_8 = QPlainTextEdit(self.gbTargetParam)
        self.tbCurrentPosJoint1_8.setObjectName(u"tbCurrentPosJoint1_8")
        self.tbCurrentPosJoint1_8.setGeometry(QRect(80, 40, 140, 31))
        self.tbCurrentPosJoint2_8 = QPlainTextEdit(self.gbTargetParam)
        self.tbCurrentPosJoint2_8.setObjectName(u"tbCurrentPosJoint2_8")
        self.tbCurrentPosJoint2_8.setGeometry(QRect(290, 100, 140, 31))
        self.lbTargetPos_Rx = QLabel(self.gbTargetParam)
        self.lbTargetPos_Rx.setObjectName(u"lbTargetPos_Rx")
        self.lbTargetPos_Rx.setGeometry(QRect(220, 100, 71, 31))
        self.lbTargetPos_Rx.setAlignment(Qt.AlignCenter)
        self.btnMoveTargetPos = QPushButton(self.gbTargetParam)
        self.btnMoveTargetPos.setObjectName(u"btnMoveTargetPos")
        self.btnMoveTargetPos.setGeometry(QRect(440, 30, 80, 110))
        self.btnSaveTargetPos = QPushButton(self.gbTargetParam)
        self.btnSaveTargetPos.setObjectName(u"btnSaveTargetPos")
        self.btnSaveTargetPos.setGeometry(QRect(550, 30, 70, 110))
        self.gbSequence = QGroupBox(MainForm)
        self.gbSequence.setObjectName(u"gbSequence")
        self.gbSequence.setGeometry(QRect(380, 630, 641, 161))
        self.btnSeq1 = QPushButton(self.gbSequence)
        self.btnSeq1.setObjectName(u"btnSeq1")
        self.btnSeq1.setGeometry(QRect(30, 50, 141, 81))
        self.btnSeq2 = QPushButton(self.gbSequence)
        self.btnSeq2.setObjectName(u"btnSeq2")
        self.btnSeq2.setGeometry(QRect(180, 50, 141, 81))
        self.btnSeq2_2 = QPushButton(self.gbSequence)
        self.btnSeq2_2.setObjectName(u"btnSeq2_2")
        self.btnSeq2_2.setGeometry(QRect(330, 50, 141, 81))

        self.retranslateUi(MainForm)
        self.btnConnect.clicked.connect(MainForm.Connect)
        self.btnMoveJoint1.clicked.connect(MainForm.MoveJoint)
        self.btnMoveJoint2.clicked.connect(MainForm.MoveJoint)
        self.btnMoveJoint3.clicked.connect(MainForm.MoveJoint)
        self.btnMoveJoint4.clicked.connect(MainForm.MoveJoint)
        self.btnMoveInitPos.clicked.connect(MainForm.MoveArm)
        self.btnSaveInitPos.clicked.connect(MainForm.Save)
        self.btnMoveWaitPos.clicked.connect(MainForm.MoveArm)
        self.btnMoveTargetPos.clicked.connect(MainForm.MoveArm)
        self.btnSaveTargetPos.clicked.connect(MainForm.Save)
        self.btnSaveWaitPos.clicked.connect(MainForm.Save)
        self.btnSeq1.clicked.connect(MainForm.DoSeq)
        self.btnSeq2.clicked.connect(MainForm.DoSeq)

        QMetaObject.connectSlotsByName(MainForm)
    # setupUi

    def retranslateUi(self, MainForm):
        MainForm.setWindowTitle(QCoreApplication.translate("MainForm", u"Form", None))
        self.gbUnit.setTitle(QCoreApplication.translate("MainForm", u"Unit", None))
        self.lbPort.setText(QCoreApplication.translate("MainForm", u"Port", None))
        self.btnConnect.setText(QCoreApplication.translate("MainForm", u"Connect", None))
        self.lbBaudRate.setText(QCoreApplication.translate("MainForm", u"BaudRate", None))
        self.gbCurrentPos.setTitle(QCoreApplication.translate("MainForm", u"Current Position", None))
        self.lbCurrentPosJoint4.setText(QCoreApplication.translate("MainForm", u"Joint4", None))
        self.lbCurrentPosJoint1.setText(QCoreApplication.translate("MainForm", u"Joint1", None))
        self.lbCurrentPosJoint2.setText(QCoreApplication.translate("MainForm", u"Joint2", None))
        self.lbCurrentPosJoint3.setText(QCoreApplication.translate("MainForm", u"Joint3", None))
        self.gbCurrentPos_2.setTitle(QCoreApplication.translate("MainForm", u"Joint Control", None))
        self.lbTargetPosJoint4.setText(QCoreApplication.translate("MainForm", u"Joint4", None))
        self.lbTargetPosJoint1.setText(QCoreApplication.translate("MainForm", u"Joint1", None))
        self.lbTargetPosJoint2.setText(QCoreApplication.translate("MainForm", u"Joint2", None))
        self.lbTargetPosJoint3.setText(QCoreApplication.translate("MainForm", u"Joint3", None))
        self.btnMoveJoint1.setText(QCoreApplication.translate("MainForm", u"Move", None))
        self.btnMoveJoint2.setText(QCoreApplication.translate("MainForm", u"Move", None))
        self.btnMoveJoint3.setText(QCoreApplication.translate("MainForm", u"Move", None))
        self.btnMoveJoint4.setText(QCoreApplication.translate("MainForm", u"Move", None))
        self.gbInitParam.setTitle(QCoreApplication.translate("MainForm", u"Inital Position", None))
        self.lbInitPos_Z.setText(QCoreApplication.translate("MainForm", u"Init Z", None))
        self.lbInitPos_X.setText(QCoreApplication.translate("MainForm", u"Init X", None))
        self.lbInitPos_Rx.setText(QCoreApplication.translate("MainForm", u"Init Rx", None))
        self.lbInitPos_Y.setText(QCoreApplication.translate("MainForm", u"Init Y", None))
        self.btnMoveInitPos.setText(QCoreApplication.translate("MainForm", u"Move", None))
        self.btnSaveInitPos.setText(QCoreApplication.translate("MainForm", u"Save", None))
        self.gbWaitParam.setTitle(QCoreApplication.translate("MainForm", u"Wait Position", None))
        self.lbWaitPos_Z.setText(QCoreApplication.translate("MainForm", u"Wait Z", None))
        self.lbWaitPos_X.setText(QCoreApplication.translate("MainForm", u"Wait X", None))
        self.lbWaitPos_Y.setText(QCoreApplication.translate("MainForm", u"Wait Y", None))
        self.lbWaitPos_Rx.setText(QCoreApplication.translate("MainForm", u"Wait Rx", None))
        self.btnMoveWaitPos.setText(QCoreApplication.translate("MainForm", u"Move", None))
        self.btnSaveWaitPos.setText(QCoreApplication.translate("MainForm", u"Save", None))
        self.gbTargetParam.setTitle(QCoreApplication.translate("MainForm", u"Target Position", None))
        self.lbTargetPos_Z.setText(QCoreApplication.translate("MainForm", u"Target Z", None))
        self.lbTargetPos_X.setText(QCoreApplication.translate("MainForm", u"Target X", None))
        self.lbTargetPos_Y.setText(QCoreApplication.translate("MainForm", u"Target Y", None))
        self.lbTargetPos_Rx.setText(QCoreApplication.translate("MainForm", u"Target Rx", None))
        self.btnMoveTargetPos.setText(QCoreApplication.translate("MainForm", u"Move", None))
        self.btnSaveTargetPos.setText(QCoreApplication.translate("MainForm", u"Save", None))
        self.gbSequence.setTitle(QCoreApplication.translate("MainForm", u"Sequence Box", None))
        self.btnSeq1.setText(QCoreApplication.translate("MainForm", u"MovetoTarget", None))
        self.btnSeq2.setText(QCoreApplication.translate("MainForm", u"Sequence 2", None))
        self.btnSeq2_2.setText(QCoreApplication.translate("MainForm", u"seq3", None))
    # retranslateUi

