init_position:
  joint_0: 178.901
  joint_1: 270.0
  joint_2: 92.0
  joint_3: 359.0
safety_position:
  joint_0: 180.0
  joint_1: 180.0
  joint_2: 126.0
  joint_3: 238.0
target_position:
  x: 650.0
  y: 0.0
  z: 350.0
wait_position:
  x: 600.0
  y: 0.0
  z: 350.0
