# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'jr_main_form.ui'
##
## Created by: Qt User Interface Compiler version 6.3.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QGroupBox, QLabel,
    QMainWindow, QPlainTextEdit, QPushButton, QSizePolicy,
    QWidget)
import os
import sys
import threading
from jeus_armcontrol import *
import yaml

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1083, 894)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gbUnit = QGroupBox(self.centralwidget)
        self.gbUnit.setObjectName(u"gbUnit")
        self.gbUnit.setGeometry(QRect(0, 10, 351, 851))
        font = QFont()
        font.setFamilies([u"Arial"])
        font.setPointSize(11)
        self.gbUnit.setFont(font)
        self.cbPort = QComboBox(self.gbUnit)
        self.cbPort.setObjectName(u"cbPort")
        self.cbPort.setGeometry(QRect(80, 20, 150, 30))
        self.lbPort = QLabel(self.gbUnit)
        self.lbPort.setObjectName(u"lbPort")
        self.lbPort.setGeometry(QRect(10, 20, 71, 31))
        self.lbPort.setAlignment(Qt.AlignCenter)
        self.btnConnect = QPushButton(self.gbUnit)
        self.btnConnect.setObjectName(u"btnConnect")
        self.btnConnect.setGeometry(QRect(240, 20, 91, 71))
        self.btnConnect.setStyleSheet(u"")
        self.lbBaudRate = QLabel(self.gbUnit)
        self.lbBaudRate.setObjectName(u"lbBaudRate")
        self.lbBaudRate.setGeometry(QRect(10, 60, 71, 31))
        self.lbBaudRate.setAlignment(Qt.AlignCenter)
        self.cbBaudRate = QComboBox(self.gbUnit)
        self.cbBaudRate.setObjectName(u"cbBaudRate")
        self.cbBaudRate.setGeometry(QRect(80, 60, 150, 30))
        self.gbCurrentPos = QGroupBox(self.gbUnit)
        self.gbCurrentPos.setObjectName(u"gbCurrentPos")
        self.gbCurrentPos.setGeometry(QRect(10, 120, 331, 221))
        self.lbCurrentPosJoint4 = QLabel(self.gbCurrentPos)
        self.lbCurrentPosJoint4.setObjectName(u"lbCurrentPosJoint4")
        self.lbCurrentPosJoint4.setGeometry(QRect(10, 180, 71, 31))
        self.lbCurrentPosJoint4.setAlignment(Qt.AlignCenter)
        self.lbCurrentPosJoint1 = QLabel(self.gbCurrentPos)
        self.lbCurrentPosJoint1.setObjectName(u"lbCurrentPosJoint1")
        self.lbCurrentPosJoint1.setGeometry(QRect(0, 30, 91, 31))
        self.lbCurrentPosJoint1.setFont(font)
        self.lbCurrentPosJoint1.setMouseTracking(False)
        self.lbCurrentPosJoint1.setAlignment(Qt.AlignCenter)
        self.lbCurrentPosJoint2 = QLabel(self.gbCurrentPos)
        self.lbCurrentPosJoint2.setObjectName(u"lbCurrentPosJoint2")
        self.lbCurrentPosJoint2.setGeometry(QRect(10, 80, 71, 31))
        self.lbCurrentPosJoint2.setAlignment(Qt.AlignCenter)
        self.tbCurrentPosJoint1 = QPlainTextEdit(self.gbCurrentPos)
        self.tbCurrentPosJoint1.setObjectName(u"tbCurrentPosJoint1")
        self.tbCurrentPosJoint1.setGeometry(QRect(100, 30, 220, 31))
        self.tbCurrentPosJoint4 = QPlainTextEdit(self.gbCurrentPos)
        self.tbCurrentPosJoint4.setObjectName(u"tbCurrentPosJoint4")
        self.tbCurrentPosJoint4.setGeometry(QRect(100, 180, 220, 31))
        self.lbCurrentPosJoint3 = QLabel(self.gbCurrentPos)
        self.lbCurrentPosJoint3.setObjectName(u"lbCurrentPosJoint3")
        self.lbCurrentPosJoint3.setGeometry(QRect(10, 130, 71, 31))
        self.lbCurrentPosJoint3.setAlignment(Qt.AlignCenter)
        self.tbCurrentPosJoint3 = QPlainTextEdit(self.gbCurrentPos)
        self.tbCurrentPosJoint3.setObjectName(u"tbCurrentPosJoint3")
        self.tbCurrentPosJoint3.setGeometry(QRect(100, 130, 220, 31))
        self.tbCurrentPosJoint2 = QPlainTextEdit(self.gbCurrentPos)
        self.tbCurrentPosJoint2.setObjectName(u"tbCurrentPosJoint2")
        self.tbCurrentPosJoint2.setGeometry(QRect(100, 80, 220, 31))
        self.gbCurrentPos_2 = QGroupBox(self.gbUnit)
        self.gbCurrentPos_2.setObjectName(u"gbCurrentPos_2")
        self.gbCurrentPos_2.setGeometry(QRect(10, 340, 331, 221))
        self.lbTargetPosJoint4 = QLabel(self.gbCurrentPos_2)
        self.lbTargetPosJoint4.setObjectName(u"lbTargetPosJoint4")
        self.lbTargetPosJoint4.setGeometry(QRect(10, 180, 51, 31))
        self.lbTargetPosJoint4.setAlignment(Qt.AlignCenter)
        self.lbTargetPosJoint1 = QLabel(self.gbCurrentPos_2)
        self.lbTargetPosJoint1.setObjectName(u"lbTargetPosJoint1")
        self.lbTargetPosJoint1.setGeometry(QRect(10, 30, 51, 31))
        self.lbTargetPosJoint1.setFont(font)
        self.lbTargetPosJoint1.setMouseTracking(False)
        self.lbTargetPosJoint1.setAlignment(Qt.AlignCenter)
        self.lbTargetPosJoint2 = QLabel(self.gbCurrentPos_2)
        self.lbTargetPosJoint2.setObjectName(u"lbTargetPosJoint2")
        self.lbTargetPosJoint2.setGeometry(QRect(10, 80, 51, 31))
        self.lbTargetPosJoint2.setAlignment(Qt.AlignCenter)
        self.tbTargetPosJoint1 = QPlainTextEdit(self.gbCurrentPos_2)
        self.tbTargetPosJoint1.setObjectName(u"tbTargetPosJoint1")
        self.tbTargetPosJoint1.setGeometry(QRect(70, 30, 140, 31))
        self.tbTargetPosJoint1.setPlainText(u"0")
        self.tbTargetPosJoint4 = QPlainTextEdit(self.gbCurrentPos_2)
        self.tbTargetPosJoint4.setObjectName(u"tbTargetPosJoint4")
        self.tbTargetPosJoint4.setGeometry(QRect(70, 180, 140, 31))
        self.tbTargetPosJoint4.setPlainText(u"0")
        self.lbTargetPosJoint3 = QLabel(self.gbCurrentPos_2)
        self.lbTargetPosJoint3.setObjectName(u"lbTargetPosJoint3")
        self.lbTargetPosJoint3.setGeometry(QRect(10, 130, 51, 31))
        self.lbTargetPosJoint3.setAlignment(Qt.AlignCenter)
        self.tbTargetPosJoint3 = QPlainTextEdit(self.gbCurrentPos_2)
        self.tbTargetPosJoint3.setObjectName(u"tbTargetPosJoint3")
        self.tbTargetPosJoint3.setGeometry(QRect(70, 130, 140, 31))
        self.tbTargetPosJoint3.setPlainText(u"0")
        self.tbTargetPosJoint2 = QPlainTextEdit(self.gbCurrentPos_2)
        self.tbTargetPosJoint2.setObjectName(u"tbTargetPosJoint2")
        self.tbTargetPosJoint2.setGeometry(QRect(70, 80, 140, 31))
        self.tbTargetPosJoint2.setPlainText(u"0")
        self.btnMoveJoint1 = QPushButton(self.gbCurrentPos_2)
        self.btnMoveJoint1.setObjectName(u"btnMoveJoint1")
        self.btnMoveJoint1.setGeometry(QRect(220, 20, 101, 41))
        self.btnMoveJoint2 = QPushButton(self.gbCurrentPos_2)
        self.btnMoveJoint2.setObjectName(u"btnMoveJoint2")
        self.btnMoveJoint2.setGeometry(QRect(220, 70, 101, 41))
        self.btnMoveJoint3 = QPushButton(self.gbCurrentPos_2)
        self.btnMoveJoint3.setObjectName(u"btnMoveJoint3")
        self.btnMoveJoint3.setGeometry(QRect(220, 120, 101, 41))
        self.btnMoveJoint4 = QPushButton(self.gbCurrentPos_2)
        self.btnMoveJoint4.setObjectName(u"btnMoveJoint4")
        self.btnMoveJoint4.setGeometry(QRect(220, 170, 101, 41))
        self.gbSequence = QGroupBox(self.centralwidget)
        self.gbSequence.setObjectName(u"gbSequence")
        self.gbSequence.setGeometry(QRect(360, 620, 641, 161))
        self.btnSeq_Push = QPushButton(self.gbSequence)
        self.btnSeq_Push.setObjectName(u"btnSeq_Push")
        self.btnSeq_Push.setGeometry(QRect(30, 50, 141, 81))
        self.btnSeq_Init = QPushButton(self.gbSequence)
        self.btnSeq_Init.setObjectName(u"btnSeq_Init")
        self.btnSeq_Init.setGeometry(QRect(180, 50, 141, 81))
        self.btnSeq_All = QPushButton(self.gbSequence)
        self.btnSeq_All.setObjectName(u"btnSeq_All")
        self.btnSeq_All.setGeometry(QRect(330, 50, 141, 81))
        self.gbInitParam = QGroupBox(self.centralwidget)
        self.gbInitParam.setObjectName(u"gbInitParam")
        self.gbInitParam.setGeometry(QRect(360, 110, 701, 161))
        self.tbInitPos_Z = QPlainTextEdit(self.gbInitParam)
        self.tbInitPos_Z.setObjectName(u"tbInitPos_Z")
        self.tbInitPos_Z.setGeometry(QRect(80, 100, 140, 31))
        self.lbInitPos_Z = QLabel(self.gbInitParam)
        self.lbInitPos_Z.setObjectName(u"lbInitPos_Z")
        self.lbInitPos_Z.setGeometry(QRect(20, 100, 51, 31))
        self.lbInitPos_Z.setAlignment(Qt.AlignCenter)
        self.tbInitPos_X = QPlainTextEdit(self.gbInitParam)
        self.tbInitPos_X.setObjectName(u"tbInitPos_X")
        self.tbInitPos_X.setGeometry(QRect(80, 40, 140, 31))
        self.lbInitPos_X = QLabel(self.gbInitParam)
        self.lbInitPos_X.setObjectName(u"lbInitPos_X")
        self.lbInitPos_X.setGeometry(QRect(20, 40, 51, 31))
        self.lbInitPos_X.setFont(font)
        self.lbInitPos_X.setMouseTracking(False)
        self.lbInitPos_X.setAlignment(Qt.AlignCenter)
        self.tbInitPos_Rx = QPlainTextEdit(self.gbInitParam)
        self.tbInitPos_Rx.setObjectName(u"tbInitPos_Rx")
        self.tbInitPos_Rx.setGeometry(QRect(290, 100, 140, 31))
        self.lbInitPos_Rx = QLabel(self.gbInitParam)
        self.lbInitPos_Rx.setObjectName(u"lbInitPos_Rx")
        self.lbInitPos_Rx.setGeometry(QRect(230, 100, 51, 31))
        self.lbInitPos_Rx.setAlignment(Qt.AlignCenter)
        self.tbInitPos_Y = QPlainTextEdit(self.gbInitParam)
        self.tbInitPos_Y.setObjectName(u"tbInitPos_Y")
        self.tbInitPos_Y.setGeometry(QRect(290, 40, 140, 31))
        self.lbInitPos_Y = QLabel(self.gbInitParam)
        self.lbInitPos_Y.setObjectName(u"lbInitPos_Y")
        self.lbInitPos_Y.setGeometry(QRect(230, 40, 51, 31))
        self.lbInitPos_Y.setFont(font)
        self.lbInitPos_Y.setMouseTracking(False)
        self.lbInitPos_Y.setAlignment(Qt.AlignCenter)
        self.btnMoveInitPos = QPushButton(self.gbInitParam)
        self.btnMoveInitPos.setObjectName(u"btnMoveInitPos")
        self.btnMoveInitPos.setGeometry(QRect(440, 30, 80, 110))
        self.btnSaveInitPos = QPushButton(self.gbInitParam)
        self.btnSaveInitPos.setObjectName(u"btnSaveInitPos")
        self.btnSaveInitPos.setGeometry(QRect(620, 30, 70, 110))
        self.gbWaitParam = QGroupBox(self.centralwidget)
        self.gbWaitParam.setObjectName(u"gbWaitParam")
        self.gbWaitParam.setGeometry(QRect(360, 280, 701, 161))
        self.lbWaitPos_Z = QLabel(self.gbWaitParam)
        self.lbWaitPos_Z.setObjectName(u"lbWaitPos_Z")
        self.lbWaitPos_Z.setGeometry(QRect(20, 100, 51, 31))
        self.lbWaitPos_Z.setAlignment(Qt.AlignCenter)
        self.tbWaitPos_Y = QPlainTextEdit(self.gbWaitParam)
        self.tbWaitPos_Y.setObjectName(u"tbWaitPos_Y")
        self.tbWaitPos_Y.setGeometry(QRect(290, 40, 140, 31))
        self.lbWaitPos_X = QLabel(self.gbWaitParam)
        self.lbWaitPos_X.setObjectName(u"lbWaitPos_X")
        self.lbWaitPos_X.setGeometry(QRect(20, 40, 51, 31))
        self.lbWaitPos_X.setFont(font)
        self.lbWaitPos_X.setMouseTracking(False)
        self.lbWaitPos_X.setAlignment(Qt.AlignCenter)
        self.lbWaitPos_Y = QLabel(self.gbWaitParam)
        self.lbWaitPos_Y.setObjectName(u"lbWaitPos_Y")
        self.lbWaitPos_Y.setGeometry(QRect(230, 40, 51, 31))
        self.lbWaitPos_Y.setFont(font)
        self.lbWaitPos_Y.setMouseTracking(False)
        self.lbWaitPos_Y.setAlignment(Qt.AlignCenter)
        self.tbWaitPos_Z = QPlainTextEdit(self.gbWaitParam)
        self.tbWaitPos_Z.setObjectName(u"tbWaitPos_Z")
        self.tbWaitPos_Z.setGeometry(QRect(80, 100, 140, 31))
        self.tbWaitPos_X = QPlainTextEdit(self.gbWaitParam)
        self.tbWaitPos_X.setObjectName(u"tbWaitPos_X")
        self.tbWaitPos_X.setGeometry(QRect(80, 40, 140, 31))
        self.tbWaitPos_Rx = QPlainTextEdit(self.gbWaitParam)
        self.tbWaitPos_Rx.setObjectName(u"tbWaitPos_Rx")
        self.tbWaitPos_Rx.setGeometry(QRect(290, 100, 140, 31))
        self.lbWaitPos_Rx = QLabel(self.gbWaitParam)
        self.lbWaitPos_Rx.setObjectName(u"lbWaitPos_Rx")
        self.lbWaitPos_Rx.setGeometry(QRect(230, 100, 51, 31))
        self.lbWaitPos_Rx.setAlignment(Qt.AlignCenter)
        self.btnMoveWaitPos = QPushButton(self.gbWaitParam)
        self.btnMoveWaitPos.setObjectName(u"btnMoveWaitPos")
        self.btnMoveWaitPos.setGeometry(QRect(440, 30, 80, 110))
        self.btnSaveWaitPos = QPushButton(self.gbWaitParam)
        self.btnSaveWaitPos.setObjectName(u"btnSaveWaitPos")
        self.btnSaveWaitPos.setGeometry(QRect(620, 30, 70, 110))
        self.gbTargetParam = QGroupBox(self.centralwidget)
        self.gbTargetParam.setObjectName(u"gbTargetParam")
        self.gbTargetParam.setGeometry(QRect(360, 450, 701, 161))
        self.lbTargetPos_Z = QLabel(self.gbTargetParam)
        self.lbTargetPos_Z.setObjectName(u"lbTargetPos_Z")
        self.lbTargetPos_Z.setGeometry(QRect(20, 100, 51, 31))
        self.lbTargetPos_Z.setAlignment(Qt.AlignCenter)
        self.tbTargetPos_Y = QPlainTextEdit(self.gbTargetParam)
        self.tbTargetPos_Y.setObjectName(u"tbTargetPos_Y")
        self.tbTargetPos_Y.setGeometry(QRect(290, 40, 140, 31))
        self.lbTargetPos_X = QLabel(self.gbTargetParam)
        self.lbTargetPos_X.setObjectName(u"lbTargetPos_X")
        self.lbTargetPos_X.setGeometry(QRect(20, 40, 51, 31))
        self.lbTargetPos_X.setFont(font)
        self.lbTargetPos_X.setMouseTracking(False)
        self.lbTargetPos_X.setAlignment(Qt.AlignCenter)
        self.lbTargetPos_Y = QLabel(self.gbTargetParam)
        self.lbTargetPos_Y.setObjectName(u"lbTargetPos_Y")
        self.lbTargetPos_Y.setGeometry(QRect(230, 40, 51, 31))
        self.lbTargetPos_Y.setFont(font)
        self.lbTargetPos_Y.setMouseTracking(False)
        self.lbTargetPos_Y.setAlignment(Qt.AlignCenter)
        self.tbTargetPos_Z = QPlainTextEdit(self.gbTargetParam)
        self.tbTargetPos_Z.setObjectName(u"tbTargetPos_Z")
        self.tbTargetPos_Z.setGeometry(QRect(80, 100, 140, 31))
        self.tbTargetPos_X = QPlainTextEdit(self.gbTargetParam)
        self.tbTargetPos_X.setObjectName(u"tbTargetPos_X")
        self.tbTargetPos_X.setGeometry(QRect(80, 40, 140, 31))
        self.tbTargetPos_Rx = QPlainTextEdit(self.gbTargetParam)
        self.tbTargetPos_Rx.setObjectName(u"tbTargetPos_Rx")
        self.tbTargetPos_Rx.setGeometry(QRect(290, 100, 140, 31))
        self.lbTargetPos_Rx = QLabel(self.gbTargetParam)
        self.lbTargetPos_Rx.setObjectName(u"lbTargetPos_Rx")
        self.lbTargetPos_Rx.setGeometry(QRect(220, 100, 71, 31))
        self.lbTargetPos_Rx.setAlignment(Qt.AlignCenter)
        self.btnMoveTargetPos_J = QPushButton(self.gbTargetParam)
        self.btnMoveTargetPos_J.setObjectName(u"btnMoveTargetPos_J")
        self.btnMoveTargetPos_J.setGeometry(QRect(440, 30, 80, 110))
        self.btnSaveTargetPos = QPushButton(self.gbTargetParam)
        self.btnSaveTargetPos.setObjectName(u"btnSaveTargetPos")
        self.btnSaveTargetPos.setGeometry(QRect(620, 30, 70, 110))
        self.btnMoveTargetPos_L = QPushButton(self.gbTargetParam)
        self.btnMoveTargetPos_L.setObjectName(u"btnMoveTargetPos_L")
        self.btnMoveTargetPos_L.setGeometry(QRect(530, 30, 80, 110))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.btnConnect.clicked.connect(MainWindow.connect_device)
        self.btnMoveJoint1.clicked.connect(MainWindow.move_joint)
        self.btnMoveJoint2.clicked.connect(MainWindow.move_joint)
        self.btnMoveJoint3.clicked.connect(MainWindow.move_joint)
        self.btnMoveJoint4.clicked.connect(MainWindow.move_joint)
        self.btnMoveWaitPos.clicked.connect(MainWindow.move_J)
        self.btnSaveTargetPos.clicked.connect(MainWindow.save)
        self.btnSaveWaitPos.clicked.connect(MainWindow.save)
        self.btnSaveInitPos.clicked.connect(MainWindow.save)
        self.btnMoveTargetPos_L.clicked.connect(MainWindow.move_L)
        self.btnMoveTargetPos_J.clicked.connect(MainWindow.move_J)
        self.btnMoveInitPos.clicked.connect(MainWindow.move_J)
        self.btnSeq_Push.clicked.connect(MainWindow.sequence_push)
        self.btnSeq_Init.clicked.connect(MainWindow.sequence_init)
        self.btnSeq_All.clicked.connect(MainWindow.sequence_all)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.gbUnit.setTitle(QCoreApplication.translate("MainWindow", u"Unit", None))
        self.lbPort.setText(QCoreApplication.translate("MainWindow", u"Port", None))
        self.btnConnect.setText(QCoreApplication.translate("MainWindow", u"Connect", None))
        self.lbBaudRate.setText(QCoreApplication.translate("MainWindow", u"BaudRate", None))
        self.gbCurrentPos.setTitle(QCoreApplication.translate("MainWindow", u"Current Position", None))
        self.lbCurrentPosJoint4.setText(QCoreApplication.translate("MainWindow", u"Joint4", None))
        self.lbCurrentPosJoint1.setText(QCoreApplication.translate("MainWindow", u"Joint1", None))
        self.lbCurrentPosJoint2.setText(QCoreApplication.translate("MainWindow", u"Joint2", None))
        self.lbCurrentPosJoint3.setText(QCoreApplication.translate("MainWindow", u"Joint3", None))
        self.gbCurrentPos_2.setTitle(QCoreApplication.translate("MainWindow", u"Joint Control", None))
        self.lbTargetPosJoint4.setText(QCoreApplication.translate("MainWindow", u"Joint4", None))
        self.lbTargetPosJoint1.setText(QCoreApplication.translate("MainWindow", u"Joint1", None))
        self.lbTargetPosJoint2.setText(QCoreApplication.translate("MainWindow", u"Joint2", None))
        self.tbTargetPosJoint1.setDocumentTitle("")
        self.lbTargetPosJoint3.setText(QCoreApplication.translate("MainWindow", u"Joint3", None))
        self.btnMoveJoint1.setText(QCoreApplication.translate("MainWindow", u"Move", None))
        self.btnMoveJoint2.setText(QCoreApplication.translate("MainWindow", u"Move", None))
        self.btnMoveJoint3.setText(QCoreApplication.translate("MainWindow", u"Move", None))
        self.btnMoveJoint4.setText(QCoreApplication.translate("MainWindow", u"Move", None))
        self.gbSequence.setTitle(QCoreApplication.translate("MainWindow", u"Sequence Box", None))
        self.btnSeq_Push.setText(QCoreApplication.translate("MainWindow", u"Push Button", None))
        self.btnSeq_Init.setText(QCoreApplication.translate("MainWindow", u"Back to Init", None))
        self.btnSeq_All.setText(QCoreApplication.translate("MainWindow", u"All Sequence", None))
        self.gbInitParam.setTitle(QCoreApplication.translate("MainWindow", u"Inital Position", None))
        self.lbInitPos_Z.setText(QCoreApplication.translate("MainWindow", u"Init Z", None))
        self.lbInitPos_X.setText(QCoreApplication.translate("MainWindow", u"Init X", None))
        self.lbInitPos_Rx.setText(QCoreApplication.translate("MainWindow", u"Init Rx", None))
        self.lbInitPos_Y.setText(QCoreApplication.translate("MainWindow", u"Init Y", None))
        self.btnMoveInitPos.setText(QCoreApplication.translate("MainWindow", u"Move", None))
        self.btnSaveInitPos.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.gbWaitParam.setTitle(QCoreApplication.translate("MainWindow", u"Wait Position", None))
        self.lbWaitPos_Z.setText(QCoreApplication.translate("MainWindow", u"Wait Z", None))
        self.lbWaitPos_X.setText(QCoreApplication.translate("MainWindow", u"Wait X", None))
        self.lbWaitPos_Y.setText(QCoreApplication.translate("MainWindow", u"Wait Y", None))
        self.lbWaitPos_Rx.setText(QCoreApplication.translate("MainWindow", u"Wait Rx", None))
        self.btnMoveWaitPos.setText(QCoreApplication.translate("MainWindow", u"Move", None))
        self.btnSaveWaitPos.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.gbTargetParam.setTitle(QCoreApplication.translate("MainWindow", u"Target Position", None))
        self.lbTargetPos_Z.setText(QCoreApplication.translate("MainWindow", u"Target Z", None))
        self.lbTargetPos_X.setText(QCoreApplication.translate("MainWindow", u"Target X", None))
        self.lbTargetPos_Y.setText(QCoreApplication.translate("MainWindow", u"Target Y", None))
        self.lbTargetPos_Rx.setText(QCoreApplication.translate("MainWindow", u"Target Rx", None))
        self.btnMoveTargetPos_J.setText(QCoreApplication.translate("MainWindow", u"J Move", None))
        self.btnSaveTargetPos.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.btnMoveTargetPos_L.setText(QCoreApplication.translate("MainWindow", u"L Move", None))
    # retranslateUi
    def setconfig(self):
        path = os.getcwd()+'\\Config'+'\\model_config'.yaml
        with open(path) as fileopen:
            model_config = yaml.load(fileopen, Loader=yaml.FullLoader)

        pass

    def set_config_posi_text(self):
        
        pass
    def get_current_pos(self):
        if hasattr(self, 'manupulator') and self.IsConnect:
            positions = self.manupulator.get_current_joints_pos()
            key_hard = sorted(positions.keys())
            
                
            
    
    def connect_device(self):
        self.manupulator = jeus_maunpulator()
        self.manupulator.get_param_value(os.path.join(os.getcwd(),'Config'),'arm_config.yaml')
        if self.manupulator.generate_module():
            self.timer = threading.Timer(0.01, self.get_current_pos)
            self.timer.start()
            self.IsConnect = True
            


    def move_joint(self):
        pass
    def move_J(self):
        pass
    def move_L(self):
        pass
    def sequence_push(self):
        pass
    def sequence_init(self):
        pass
    def sequence_all(self):
        pass

    def save(self):
        pass
