# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'jr_main_form.ui'
##
## Created by: Qt User Interface Compiler version 6.3.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QGroupBox, QLabel,
    QMainWindow, QPlainTextEdit, QPushButton, QSizePolicy,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1083, 894)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gbUnit = QGroupBox(self.centralwidget)
        self.gbUnit.setObjectName(u"gbUnit")
        self.gbUnit.setGeometry(QRect(0, 10, 351, 851))
        font = QFont()
        font.setFamilies([u"Arial"])
        font.setPointSize(11)
        self.gbUnit.setFont(font)
        self.cbPort = QComboBox(self.gbUnit)
        self.cbPort.setObjectName(u"cbPort")
        self.cbPort.setGeometry(QRect(80, 20, 150, 30))
        self.lbPort = QLabel(self.gbUnit)
        self.lbPort.setObjectName(u"lbPort")
        self.lbPort.setGeometry(QRect(10, 20, 71, 31))
        self.lbPort.setAlignment(Qt.AlignCenter)
        self.btnConnect = QPushButton(self.gbUnit)
        self.btnConnect.setObjectName(u"btnConnect")
        self.btnConnect.setGeometry(QRect(240, 20, 91, 71))
        self.btnConnect.setStyleSheet(u"")
        self.lbBaudRate = QLabel(self.gbUnit)
        self.lbBaudRate.setObjectName(u"lbBaudRate")
        self.lbBaudRate.setGeometry(QRect(10, 60, 71, 31))
        self.lbBaudRate.setAlignment(Qt.AlignCenter)
        self.cbBaudRate = QComboBox(self.gbUnit)
        self.cbBaudRate.setObjectName(u"cbBaudRate")
        self.cbBaudRate.setGeometry(QRect(80, 60, 150, 30))
        self.gbCurrentPos = QGroupBox(self.gbUnit)
        self.gbCurrentPos.setObjectName(u"gbCurrentPos")
        self.gbCurrentPos.setGeometry(QRect(10, 120, 331, 221))
        self.lbCurrentPosJoint4 = QLabel(self.gbCurrentPos)
        self.lbCurrentPosJoint4.setObjectName(u"lbCurrentPosJoint4")
        self.lbCurrentPosJoint4.setGeometry(QRect(10, 180, 71, 31))
        self.lbCurrentPosJoint4.setAlignment(Qt.AlignCenter)
        self.lbCurrentPosJoint1 = QLabel(self.gbCurrentPos)
        self.lbCurrentPosJoint1.setObjectName(u"lbCurrentPosJoint1")
        self.lbCurrentPosJoint1.setGeometry(QRect(0, 30, 91, 31))
        self.lbCurrentPosJoint1.setFont(font)
        self.lbCurrentPosJoint1.setMouseTracking(False)
        self.lbCurrentPosJoint1.setAlignment(Qt.AlignCenter)
        self.lbCurrentPosJoint2 = QLabel(self.gbCurrentPos)
        self.lbCurrentPosJoint2.setObjectName(u"lbCurrentPosJoint2")
        self.lbCurrentPosJoint2.setGeometry(QRect(10, 80, 71, 31))
        self.lbCurrentPosJoint2.setAlignment(Qt.AlignCenter)
        self.tbCurrentPosJoint1 = QPlainTextEdit(self.gbCurrentPos)
        self.tbCurrentPosJoint1.setObjectName(u"tbCurrentPosJoint1")
        self.tbCurrentPosJoint1.setGeometry(QRect(100, 30, 111, 31))
        self.tbCurrentPosJoint4 = QPlainTextEdit(self.gbCurrentPos)
        self.tbCurrentPosJoint4.setObjectName(u"tbCurrentPosJoint4")
        self.tbCurrentPosJoint4.setGeometry(QRect(100, 180, 111, 31))
        self.lbCurrentPosJoint3 = QLabel(self.gbCurrentPos)
        self.lbCurrentPosJoint3.setObjectName(u"lbCurrentPosJoint3")
        self.lbCurrentPosJoint3.setGeometry(QRect(10, 130, 71, 31))
        self.lbCurrentPosJoint3.setAlignment(Qt.AlignCenter)
        self.tbCurrentPosJoint3 = QPlainTextEdit(self.gbCurrentPos)
        self.tbCurrentPosJoint3.setObjectName(u"tbCurrentPosJoint3")
        self.tbCurrentPosJoint3.setGeometry(QRect(100, 130, 111, 31))
        self.tbCurrentPosJoint2 = QPlainTextEdit(self.gbCurrentPos)
        self.tbCurrentPosJoint2.setObjectName(u"tbCurrentPosJoint2")
        self.tbCurrentPosJoint2.setGeometry(QRect(100, 80, 111, 31))
        self.btntorqueonoff_0 = QPushButton(self.gbCurrentPos)
        self.btntorqueonoff_0.setObjectName(u"btntorqueonoff_0")
        self.btntorqueonoff_0.setGeometry(QRect(220, 25, 101, 40))
        self.btntorqueonoff_1 = QPushButton(self.gbCurrentPos)
        self.btntorqueonoff_1.setObjectName(u"btntorqueonoff_1")
        self.btntorqueonoff_1.setGeometry(QRect(220, 77, 101, 40))
        self.btntorqueonoff_2 = QPushButton(self.gbCurrentPos)
        self.btntorqueonoff_2.setObjectName(u"btntorqueonoff_2")
        self.btntorqueonoff_2.setGeometry(QRect(220, 127, 101, 40))
        self.btntorqueonoff_3 = QPushButton(self.gbCurrentPos)
        self.btntorqueonoff_3.setObjectName(u"btntorqueonoff_3")
        self.btntorqueonoff_3.setGeometry(QRect(220, 174, 101, 40))
        self.gbCurrentPos_2 = QGroupBox(self.gbUnit)
        self.gbCurrentPos_2.setObjectName(u"gbCurrentPos_2")
        self.gbCurrentPos_2.setGeometry(QRect(10, 340, 331, 221))
        self.lbTargetPosJoint4 = QLabel(self.gbCurrentPos_2)
        self.lbTargetPosJoint4.setObjectName(u"lbTargetPosJoint4")
        self.lbTargetPosJoint4.setGeometry(QRect(10, 180, 51, 31))
        self.lbTargetPosJoint4.setAlignment(Qt.AlignCenter)
        self.lbTargetPosJoint1 = QLabel(self.gbCurrentPos_2)
        self.lbTargetPosJoint1.setObjectName(u"lbTargetPosJoint1")
        self.lbTargetPosJoint1.setGeometry(QRect(10, 30, 51, 31))
        self.lbTargetPosJoint1.setFont(font)
        self.lbTargetPosJoint1.setMouseTracking(False)
        self.lbTargetPosJoint1.setAlignment(Qt.AlignCenter)
        self.lbTargetPosJoint2 = QLabel(self.gbCurrentPos_2)
        self.lbTargetPosJoint2.setObjectName(u"lbTargetPosJoint2")
        self.lbTargetPosJoint2.setGeometry(QRect(10, 80, 51, 31))
        self.lbTargetPosJoint2.setAlignment(Qt.AlignCenter)
        self.tbTargetPosJoint_0 = QPlainTextEdit(self.gbCurrentPos_2)
        self.tbTargetPosJoint_0.setObjectName(u"tbTargetPosJoint_0")
        self.tbTargetPosJoint_0.setGeometry(QRect(70, 30, 140, 31))
        self.tbTargetPosJoint_0.setPlainText(u"0")
        self.tbTargetPosJoint_3 = QPlainTextEdit(self.gbCurrentPos_2)
        self.tbTargetPosJoint_3.setObjectName(u"tbTargetPosJoint_3")
        self.tbTargetPosJoint_3.setGeometry(QRect(70, 180, 140, 31))
        self.tbTargetPosJoint_3.setPlainText(u"0")
        self.lbTargetPosJoint3 = QLabel(self.gbCurrentPos_2)
        self.lbTargetPosJoint3.setObjectName(u"lbTargetPosJoint3")
        self.lbTargetPosJoint3.setGeometry(QRect(10, 130, 51, 31))
        self.lbTargetPosJoint3.setAlignment(Qt.AlignCenter)
        self.tbTargetPosJoint_2 = QPlainTextEdit(self.gbCurrentPos_2)
        self.tbTargetPosJoint_2.setObjectName(u"tbTargetPosJoint_2")
        self.tbTargetPosJoint_2.setGeometry(QRect(70, 130, 140, 31))
        self.tbTargetPosJoint_2.setPlainText(u"0")
        self.tbTargetPosJoint_1 = QPlainTextEdit(self.gbCurrentPos_2)
        self.tbTargetPosJoint_1.setObjectName(u"tbTargetPosJoint_1")
        self.tbTargetPosJoint_1.setGeometry(QRect(70, 80, 140, 31))
        self.tbTargetPosJoint_1.setPlainText(u"0")
        self.btnMoveJoint_0 = QPushButton(self.gbCurrentPos_2)
        self.btnMoveJoint_0.setObjectName(u"btnMoveJoint_0")
        self.btnMoveJoint_0.setGeometry(QRect(220, 20, 101, 41))
        self.btnMoveJoint_1 = QPushButton(self.gbCurrentPos_2)
        self.btnMoveJoint_1.setObjectName(u"btnMoveJoint_1")
        self.btnMoveJoint_1.setGeometry(QRect(220, 70, 101, 41))
        self.btnMoveJoint_2 = QPushButton(self.gbCurrentPos_2)
        self.btnMoveJoint_2.setObjectName(u"btnMoveJoint_2")
        self.btnMoveJoint_2.setGeometry(QRect(220, 120, 101, 41))
        self.btnMoveJoint_3 = QPushButton(self.gbCurrentPos_2)
        self.btnMoveJoint_3.setObjectName(u"btnMoveJoint_3")
        self.btnMoveJoint_3.setGeometry(QRect(220, 170, 101, 41))
        self.gbCurrentPos_3 = QGroupBox(self.gbUnit)
        self.gbCurrentPos_3.setObjectName(u"gbCurrentPos_3")
        self.gbCurrentPos_3.setGeometry(QRect(10, 570, 331, 221))
        self.lbCurrent_X = QLabel(self.gbCurrentPos_3)
        self.lbCurrent_X.setObjectName(u"lbCurrent_X")
        self.lbCurrent_X.setGeometry(QRect(0, 30, 91, 31))
        self.lbCurrent_X.setFont(font)
        self.lbCurrent_X.setMouseTracking(False)
        self.lbCurrent_X.setAlignment(Qt.AlignCenter)
        self.lbCurrent_Y = QLabel(self.gbCurrentPos_3)
        self.lbCurrent_Y.setObjectName(u"lbCurrent_Y")
        self.lbCurrent_Y.setGeometry(QRect(10, 80, 71, 31))
        self.lbCurrent_Y.setAlignment(Qt.AlignCenter)
        self.tbCurrent_X = QPlainTextEdit(self.gbCurrentPos_3)
        self.tbCurrent_X.setObjectName(u"tbCurrent_X")
        self.tbCurrent_X.setGeometry(QRect(100, 30, 181, 31))
        self.lbCurrent_Z = QLabel(self.gbCurrentPos_3)
        self.lbCurrent_Z.setObjectName(u"lbCurrent_Z")
        self.lbCurrent_Z.setGeometry(QRect(10, 130, 71, 31))
        self.lbCurrent_Z.setAlignment(Qt.AlignCenter)
        self.tbCurrent_Z = QPlainTextEdit(self.gbCurrentPos_3)
        self.tbCurrent_Z.setObjectName(u"tbCurrent_Z")
        self.tbCurrent_Z.setGeometry(QRect(100, 130, 181, 31))
        self.tbCurrent_Y = QPlainTextEdit(self.gbCurrentPos_3)
        self.tbCurrent_Y.setObjectName(u"tbCurrent_Y")
        self.tbCurrent_Y.setGeometry(QRect(100, 80, 181, 31))
        self.btncalculate_xyz = QPushButton(self.gbCurrentPos_3)
        self.btncalculate_xyz.setObjectName(u"btncalculate_xyz")
        self.btncalculate_xyz.setGeometry(QRect(30, 170, 251, 40))
        self.gbSequence = QGroupBox(self.centralwidget)
        self.gbSequence.setObjectName(u"gbSequence")
        self.gbSequence.setGeometry(QRect(360, 690, 641, 161))
        self.btnSeq_SelectBtn = QPushButton(self.gbSequence)
        self.btnSeq_SelectBtn.setObjectName(u"btnSeq_SelectBtn")
        self.btnSeq_SelectBtn.setGeometry(QRect(30, 70, 141, 81))
        self.btnSeq_Pushbtn = QPushButton(self.gbSequence)
        self.btnSeq_Pushbtn.setObjectName(u"btnSeq_Pushbtn")
        self.btnSeq_Pushbtn.setGeometry(QRect(180, 70, 141, 81))
        self.btnSeq_All = QPushButton(self.gbSequence)
        self.btnSeq_All.setObjectName(u"btnSeq_All")
        self.btnSeq_All.setGeometry(QRect(450, 70, 141, 81))
        self.tbFloor = QPlainTextEdit(self.gbSequence)
        self.tbFloor.setObjectName(u"tbFloor")
        self.tbFloor.setGeometry(QRect(120, 30, 201, 31))
        self.lbCurrent_Z_2 = QLabel(self.gbSequence)
        self.lbCurrent_Z_2.setObjectName(u"lbCurrent_Z_2")
        self.lbCurrent_Z_2.setGeometry(QRect(30, 30, 71, 31))
        self.lbCurrent_Z_2.setAlignment(Qt.AlignCenter)
        self.gbInitParam = QGroupBox(self.centralwidget)
        self.gbInitParam.setObjectName(u"gbInitParam")
        self.gbInitParam.setGeometry(QRect(360, 10, 701, 161))
        self.tbInitPos_2 = QPlainTextEdit(self.gbInitParam)
        self.tbInitPos_2.setObjectName(u"tbInitPos_2")
        self.tbInitPos_2.setGeometry(QRect(89, 100, 131, 31))
        self.lbInitPos_Z = QLabel(self.gbInitParam)
        self.lbInitPos_Z.setObjectName(u"lbInitPos_Z")
        self.lbInitPos_Z.setGeometry(QRect(20, 100, 51, 31))
        self.lbInitPos_Z.setFont(font)
        self.lbInitPos_Z.setAlignment(Qt.AlignCenter)
        self.tbInitPos_0 = QPlainTextEdit(self.gbInitParam)
        self.tbInitPos_0.setObjectName(u"tbInitPos_0")
        self.tbInitPos_0.setGeometry(QRect(89, 40, 131, 31))
        self.lbInitPos_X = QLabel(self.gbInitParam)
        self.lbInitPos_X.setObjectName(u"lbInitPos_X")
        self.lbInitPos_X.setGeometry(QRect(20, 40, 51, 31))
        self.lbInitPos_X.setFont(font)
        self.lbInitPos_X.setMouseTracking(False)
        self.lbInitPos_X.setAlignment(Qt.AlignCenter)
        self.tbInitPos_3 = QPlainTextEdit(self.gbInitParam)
        self.tbInitPos_3.setObjectName(u"tbInitPos_3")
        self.tbInitPos_3.setGeometry(QRect(299, 100, 131, 31))
        self.lbInitPos_Rx = QLabel(self.gbInitParam)
        self.lbInitPos_Rx.setObjectName(u"lbInitPos_Rx")
        self.lbInitPos_Rx.setGeometry(QRect(230, 100, 51, 31))
        self.lbInitPos_Rx.setFont(font)
        self.lbInitPos_Rx.setAlignment(Qt.AlignCenter)
        self.tbInitPos_1 = QPlainTextEdit(self.gbInitParam)
        self.tbInitPos_1.setObjectName(u"tbInitPos_1")
        self.tbInitPos_1.setGeometry(QRect(299, 40, 131, 31))
        self.lbInitPos_Y = QLabel(self.gbInitParam)
        self.lbInitPos_Y.setObjectName(u"lbInitPos_Y")
        self.lbInitPos_Y.setGeometry(QRect(230, 40, 51, 31))
        self.lbInitPos_Y.setFont(font)
        self.lbInitPos_Y.setMouseTracking(False)
        self.lbInitPos_Y.setAlignment(Qt.AlignCenter)
        self.btnMoveInitPos = QPushButton(self.gbInitParam)
        self.btnMoveInitPos.setObjectName(u"btnMoveInitPos")
        self.btnMoveInitPos.setGeometry(QRect(440, 30, 80, 110))
        self.btnSaveInitPos = QPushButton(self.gbInitParam)
        self.btnSaveInitPos.setObjectName(u"btnSaveInitPos")
        self.btnSaveInitPos.setGeometry(QRect(620, 30, 70, 110))
        self.gbWaitParam = QGroupBox(self.centralwidget)
        self.gbWaitParam.setObjectName(u"gbWaitParam")
        self.gbWaitParam.setGeometry(QRect(360, 350, 701, 161))
        self.lbWaitPos_Z = QLabel(self.gbWaitParam)
        self.lbWaitPos_Z.setObjectName(u"lbWaitPos_Z")
        self.lbWaitPos_Z.setGeometry(QRect(20, 100, 51, 31))
        self.lbWaitPos_Z.setFont(font)
        self.lbWaitPos_Z.setAlignment(Qt.AlignCenter)
        self.tbWaitPos_Y = QPlainTextEdit(self.gbWaitParam)
        self.tbWaitPos_Y.setObjectName(u"tbWaitPos_Y")
        self.tbWaitPos_Y.setGeometry(QRect(299, 40, 131, 31))
        self.lbWaitPos_X = QLabel(self.gbWaitParam)
        self.lbWaitPos_X.setObjectName(u"lbWaitPos_X")
        self.lbWaitPos_X.setGeometry(QRect(20, 40, 51, 31))
        self.lbWaitPos_X.setFont(font)
        self.lbWaitPos_X.setMouseTracking(False)
        self.lbWaitPos_X.setAlignment(Qt.AlignCenter)
        self.lbWaitPos_Y = QLabel(self.gbWaitParam)
        self.lbWaitPos_Y.setObjectName(u"lbWaitPos_Y")
        self.lbWaitPos_Y.setGeometry(QRect(230, 40, 51, 31))
        self.lbWaitPos_Y.setFont(font)
        self.lbWaitPos_Y.setMouseTracking(False)
        self.lbWaitPos_Y.setAlignment(Qt.AlignCenter)
        self.tbWaitPos_Z = QPlainTextEdit(self.gbWaitParam)
        self.tbWaitPos_Z.setObjectName(u"tbWaitPos_Z")
        self.tbWaitPos_Z.setGeometry(QRect(89, 100, 131, 31))
        self.tbWaitPos_X = QPlainTextEdit(self.gbWaitParam)
        self.tbWaitPos_X.setObjectName(u"tbWaitPos_X")
        self.tbWaitPos_X.setGeometry(QRect(89, 40, 131, 31))
        self.btnMoveWaitPos = QPushButton(self.gbWaitParam)
        self.btnMoveWaitPos.setObjectName(u"btnMoveWaitPos")
        self.btnMoveWaitPos.setGeometry(QRect(440, 30, 80, 110))
        self.btnSaveWaitPos = QPushButton(self.gbWaitParam)
        self.btnSaveWaitPos.setObjectName(u"btnSaveWaitPos")
        self.btnSaveWaitPos.setGeometry(QRect(620, 30, 70, 110))
        self.gbTargetParam = QGroupBox(self.centralwidget)
        self.gbTargetParam.setObjectName(u"gbTargetParam")
        self.gbTargetParam.setGeometry(QRect(360, 520, 701, 161))
        self.lbTargetPos_Z = QLabel(self.gbTargetParam)
        self.lbTargetPos_Z.setObjectName(u"lbTargetPos_Z")
        self.lbTargetPos_Z.setGeometry(QRect(20, 100, 51, 31))
        self.lbTargetPos_Z.setFont(font)
        self.lbTargetPos_Z.setAlignment(Qt.AlignCenter)
        self.tbTargetPos_Y = QPlainTextEdit(self.gbTargetParam)
        self.tbTargetPos_Y.setObjectName(u"tbTargetPos_Y")
        self.tbTargetPos_Y.setGeometry(QRect(290, 40, 140, 31))
        self.lbTargetPos_X = QLabel(self.gbTargetParam)
        self.lbTargetPos_X.setObjectName(u"lbTargetPos_X")
        self.lbTargetPos_X.setGeometry(QRect(20, 40, 51, 31))
        self.lbTargetPos_X.setFont(font)
        self.lbTargetPos_X.setMouseTracking(False)
        self.lbTargetPos_X.setAlignment(Qt.AlignCenter)
        self.lbTargetPos_Y = QLabel(self.gbTargetParam)
        self.lbTargetPos_Y.setObjectName(u"lbTargetPos_Y")
        self.lbTargetPos_Y.setGeometry(QRect(230, 40, 51, 31))
        self.lbTargetPos_Y.setFont(font)
        self.lbTargetPos_Y.setMouseTracking(False)
        self.lbTargetPos_Y.setAlignment(Qt.AlignCenter)
        self.tbTargetPos_Z = QPlainTextEdit(self.gbTargetParam)
        self.tbTargetPos_Z.setObjectName(u"tbTargetPos_Z")
        self.tbTargetPos_Z.setGeometry(QRect(80, 100, 140, 31))
        self.tbTargetPos_X = QPlainTextEdit(self.gbTargetParam)
        self.tbTargetPos_X.setObjectName(u"tbTargetPos_X")
        self.tbTargetPos_X.setGeometry(QRect(80, 40, 140, 31))
        self.btnMoveTargetPos_J = QPushButton(self.gbTargetParam)
        self.btnMoveTargetPos_J.setObjectName(u"btnMoveTargetPos_J")
        self.btnMoveTargetPos_J.setGeometry(QRect(440, 30, 80, 110))
        self.btnSaveTargetPos = QPushButton(self.gbTargetParam)
        self.btnSaveTargetPos.setObjectName(u"btnSaveTargetPos")
        self.btnSaveTargetPos.setGeometry(QRect(620, 30, 70, 110))
        self.btnMoveTargetPos_L = QPushButton(self.gbTargetParam)
        self.btnMoveTargetPos_L.setObjectName(u"btnMoveTargetPos_L")
        self.btnMoveTargetPos_L.setGeometry(QRect(530, 30, 80, 110))
        self.gbsafetyParam = QGroupBox(self.centralwidget)
        self.gbsafetyParam.setObjectName(u"gbsafetyParam")
        self.gbsafetyParam.setGeometry(QRect(360, 180, 701, 161))
        self.tbSafetyPos_2 = QPlainTextEdit(self.gbsafetyParam)
        self.tbSafetyPos_2.setObjectName(u"tbSafetyPos_2")
        self.tbSafetyPos_2.setGeometry(QRect(89, 100, 131, 31))
        self.lbSafetyPos_2 = QLabel(self.gbsafetyParam)
        self.lbSafetyPos_2.setObjectName(u"lbSafetyPos_2")
        self.lbSafetyPos_2.setGeometry(QRect(20, 100, 61, 31))
        self.lbSafetyPos_2.setFont(font)
        self.lbSafetyPos_2.setAlignment(Qt.AlignCenter)
        self.tbSafetyPos_0 = QPlainTextEdit(self.gbsafetyParam)
        self.tbSafetyPos_0.setObjectName(u"tbSafetyPos_0")
        self.tbSafetyPos_0.setGeometry(QRect(89, 40, 131, 31))
        self.lbSafetyPos_0 = QLabel(self.gbsafetyParam)
        self.lbSafetyPos_0.setObjectName(u"lbSafetyPos_0")
        self.lbSafetyPos_0.setGeometry(QRect(20, 40, 61, 31))
        self.lbSafetyPos_0.setFont(font)
        self.lbSafetyPos_0.setMouseTracking(False)
        self.lbSafetyPos_0.setAlignment(Qt.AlignCenter)
        self.tbSafetyPos_3 = QPlainTextEdit(self.gbsafetyParam)
        self.tbSafetyPos_3.setObjectName(u"tbSafetyPos_3")
        self.tbSafetyPos_3.setGeometry(QRect(299, 100, 131, 31))
        self.lbSafetyPos_4 = QLabel(self.gbsafetyParam)
        self.lbSafetyPos_4.setObjectName(u"lbSafetyPos_4")
        self.lbSafetyPos_4.setGeometry(QRect(230, 100, 61, 31))
        self.lbSafetyPos_4.setFont(font)
        self.lbSafetyPos_4.setAlignment(Qt.AlignCenter)
        self.tbSafetyPos_1 = QPlainTextEdit(self.gbsafetyParam)
        self.tbSafetyPos_1.setObjectName(u"tbSafetyPos_1")
        self.tbSafetyPos_1.setGeometry(QRect(299, 40, 131, 31))
        self.lbSafetyPos_1 = QLabel(self.gbsafetyParam)
        self.lbSafetyPos_1.setObjectName(u"lbSafetyPos_1")
        self.lbSafetyPos_1.setGeometry(QRect(220, 40, 71, 31))
        self.lbSafetyPos_1.setFont(font)
        self.lbSafetyPos_1.setMouseTracking(False)
        self.lbSafetyPos_1.setAlignment(Qt.AlignCenter)
        self.btnMoveSafetyPos = QPushButton(self.gbsafetyParam)
        self.btnMoveSafetyPos.setObjectName(u"btnMoveSafetyPos")
        self.btnMoveSafetyPos.setGeometry(QRect(440, 30, 80, 110))
        self.btnSaveSafetyPos = QPushButton(self.gbsafetyParam)
        self.btnSaveSafetyPos.setObjectName(u"btnSaveSafetyPos")
        self.btnSaveSafetyPos.setGeometry(QRect(620, 30, 70, 110))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.btnConnect.clicked.connect(MainWindow.connect_device)
        self.btnMoveJoint_0.clicked.connect(MainWindow.move_joint)
        self.btnMoveJoint_1.clicked.connect(MainWindow.move_joint)
        self.btnMoveJoint_2.clicked.connect(MainWindow.move_joint)
        self.btnMoveJoint_3.clicked.connect(MainWindow.move_joint)
        self.btnMoveWaitPos.clicked.connect(MainWindow.move_J)
        self.btnSaveTargetPos.clicked.connect(MainWindow.save)
        self.btnSaveWaitPos.clicked.connect(MainWindow.save)
        self.btnSaveInitPos.clicked.connect(MainWindow.save)
        self.btnMoveTargetPos_L.clicked.connect(MainWindow.move_L)
        self.btnMoveTargetPos_J.clicked.connect(MainWindow.move_J)
        self.btnMoveInitPos.clicked.connect(MainWindow.move_J)
        self.btnSeq_SelectBtn.clicked.connect(MainWindow.sequence_DetectBtn)
        self.btnSeq_Pushbtn.clicked.connect(MainWindow.sequence_PushBtn)
        self.btnSeq_All.clicked.connect(MainWindow.sequence_all)
        self.btntorqueonoff_0.clicked.connect(MainWindow.torque_onoff)
        self.btntorqueonoff_1.clicked.connect(MainWindow.torque_onoff)
        self.btntorqueonoff_2.clicked.connect(MainWindow.torque_onoff)
        self.btntorqueonoff_3.clicked.connect(MainWindow.torque_onoff)
        self.btncalculate_xyz.clicked.connect(MainWindow.calculate_xyz)
        self.btnMoveSafetyPos.clicked.connect(MainWindow.move_J)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.gbUnit.setTitle(QCoreApplication.translate("MainWindow", u"Unit", None))
        self.lbPort.setText(QCoreApplication.translate("MainWindow", u"Port", None))
        self.btnConnect.setText(QCoreApplication.translate("MainWindow", u"Connect", None))
        self.lbBaudRate.setText(QCoreApplication.translate("MainWindow", u"BaudRate", None))
        self.gbCurrentPos.setTitle(QCoreApplication.translate("MainWindow", u"Current Position", None))
        self.lbCurrentPosJoint4.setText(QCoreApplication.translate("MainWindow", u"Joint4", None))
        self.lbCurrentPosJoint1.setText(QCoreApplication.translate("MainWindow", u"Joint1", None))
        self.lbCurrentPosJoint2.setText(QCoreApplication.translate("MainWindow", u"Joint2", None))
        self.lbCurrentPosJoint3.setText(QCoreApplication.translate("MainWindow", u"Joint3", None))
        self.btntorqueonoff_0.setText(QCoreApplication.translate("MainWindow", u"Torque On/Off", None))
        self.btntorqueonoff_1.setText(QCoreApplication.translate("MainWindow", u"Torque On/Off", None))
        self.btntorqueonoff_2.setText(QCoreApplication.translate("MainWindow", u"Torque On/Off", None))
        self.btntorqueonoff_3.setText(QCoreApplication.translate("MainWindow", u"Torque On/Off", None))
        self.gbCurrentPos_2.setTitle(QCoreApplication.translate("MainWindow", u"Joint Control", None))
        self.lbTargetPosJoint4.setText(QCoreApplication.translate("MainWindow", u"Joint4", None))
        self.lbTargetPosJoint1.setText(QCoreApplication.translate("MainWindow", u"Joint1", None))
        self.lbTargetPosJoint2.setText(QCoreApplication.translate("MainWindow", u"Joint2", None))
        self.tbTargetPosJoint_0.setDocumentTitle("")
        self.lbTargetPosJoint3.setText(QCoreApplication.translate("MainWindow", u"Joint3", None))
        self.btnMoveJoint_0.setText(QCoreApplication.translate("MainWindow", u"Move", None))
        self.btnMoveJoint_1.setText(QCoreApplication.translate("MainWindow", u"Move", None))
        self.btnMoveJoint_2.setText(QCoreApplication.translate("MainWindow", u"Move", None))
        self.btnMoveJoint_3.setText(QCoreApplication.translate("MainWindow", u"Move", None))
        self.gbCurrentPos_3.setTitle(QCoreApplication.translate("MainWindow", u"calculate position", None))
        self.lbCurrent_X.setText(QCoreApplication.translate("MainWindow", u"x", None))
        self.lbCurrent_Y.setText(QCoreApplication.translate("MainWindow", u"y", None))
        self.lbCurrent_Z.setText(QCoreApplication.translate("MainWindow", u"z", None))
        self.btncalculate_xyz.setText(QCoreApplication.translate("MainWindow", u"calculate x,y,z", None))
        self.gbSequence.setTitle(QCoreApplication.translate("MainWindow", u"Sequence Box", None))
        self.btnSeq_SelectBtn.setText(QCoreApplication.translate("MainWindow", u"Detect Button", None))
        self.btnSeq_Pushbtn.setText(QCoreApplication.translate("MainWindow", u"Push Button Seq", None))
        self.btnSeq_All.setText(QCoreApplication.translate("MainWindow", u"All Sequence", None))
        self.lbCurrent_Z_2.setText(QCoreApplication.translate("MainWindow", u"Floor", None))
        self.gbInitParam.setTitle(QCoreApplication.translate("MainWindow", u"Inital Position", None))
        self.lbInitPos_Z.setText(QCoreApplication.translate("MainWindow", u"Init Z", None))
        self.lbInitPos_X.setText(QCoreApplication.translate("MainWindow", u"Init X", None))
        self.lbInitPos_Rx.setText(QCoreApplication.translate("MainWindow", u"Init Ry", None))
        self.lbInitPos_Y.setText(QCoreApplication.translate("MainWindow", u"Init Y", None))
        self.btnMoveInitPos.setText(QCoreApplication.translate("MainWindow", u"Move", None))
        self.btnSaveInitPos.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.gbWaitParam.setTitle(QCoreApplication.translate("MainWindow", u"Wait Position", None))
        self.lbWaitPos_Z.setText(QCoreApplication.translate("MainWindow", u"Wait Z", None))
        self.lbWaitPos_X.setText(QCoreApplication.translate("MainWindow", u"Wait X", None))
        self.lbWaitPos_Y.setText(QCoreApplication.translate("MainWindow", u"Wait Y", None))
        self.btnMoveWaitPos.setText(QCoreApplication.translate("MainWindow", u"Move", None))
        self.btnSaveWaitPos.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.gbTargetParam.setTitle(QCoreApplication.translate("MainWindow", u"Target Position", None))
        self.lbTargetPos_Z.setText(QCoreApplication.translate("MainWindow", u"Target Z", None))
        self.lbTargetPos_X.setText(QCoreApplication.translate("MainWindow", u"Target X", None))
        self.lbTargetPos_Y.setText(QCoreApplication.translate("MainWindow", u"Target Y", None))
        self.btnMoveTargetPos_J.setText(QCoreApplication.translate("MainWindow", u"J Move", None))
        self.btnSaveTargetPos.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.btnMoveTargetPos_L.setText(QCoreApplication.translate("MainWindow", u"L Move", None))
        self.gbsafetyParam.setTitle(QCoreApplication.translate("MainWindow", u"Safety Position", None))
        self.lbSafetyPos_2.setText(QCoreApplication.translate("MainWindow", u"Safety J3", None))
        self.lbSafetyPos_0.setText(QCoreApplication.translate("MainWindow", u"Safety J1", None))
        self.lbSafetyPos_4.setText(QCoreApplication.translate("MainWindow", u"Safety J4", None))
        self.lbSafetyPos_1.setText(QCoreApplication.translate("MainWindow", u"Safety J2", None))
        self.btnMoveSafetyPos.setText(QCoreApplication.translate("MainWindow", u"Move", None))
        self.btnSaveSafetyPos.setText(QCoreApplication.translate("MainWindow", u"Save", None))
    # retranslateUi

